### ISSUE TITLE
Criar Json Schema - Escolher (10 Pontos)

### ISSUE THREAD

**Issue by johnt1000** [CoticEaDIFRN/ms_integrador_moodle_suap#23]
Criar JSON Schema para recurso de escolher que será implementado na API SUAP.

Especificação: [https://json-schema.org](https://json-schema.org)
Referência:
```json
[
    "professores": [
        {
            "...": '...'
        }
    ],
    "alunos": [
        {
            "...": '...'
        }
    ]
]
```

**Comment by Doginnn** [comment]
Realizado a criação do do JSON Schema.
