### ISSUE TITLE
Manter Curso - 5 Pontos

### ISSUE THREAD

**Issue by johnt1000** [CoticEaDIFRN/ms_integrador_moodle_suap#3]
Criar um CRUD da entidade curso, considerando a estrutura do Moodle e do SUAP.

O curso deve contemplar os seguintes campos:
1. ID (PK);
2. Nome do Curso;
3. Código do Campus (FK);
4. Código do Moodle;
5. Código do SUAP;

**Comment by Doginnn** [comment]
Feito a implementação de CURSO.
