### ISSUE TITLE
Manter Campus - 3 Pontos

### ISSUE THREAD

**Issue by johnt1000** [CoticEaDIFRN/ms_integrador_moodle_suap#4]
Criar um CRUD da entidade campus, considerando a estrutura do Moodle e do SUAP.

O campus deve contemplar os seguintes campos:

1. ID (PK);
2. Nome do Campus;
3. Código do Moodle;
4. Código do SUAP;

**Comment by Doginnn** [comment]
Feito a implementação de CAMPUS
